#!/usr/bin/env bash

set -euo pipefail

XSHELL="$1"; shift
INPUT="$1"; shift
OUTPUT="$(mktemp ".$(basename "$INPUT")-XXXX")"
cleanup() { rm "$OUTPUT"; }

lenker "$INPUT" "$OUTPUT" | (grep -v "Wrote: $OUTPUT" || :)
trap cleanup EXIT

$XSHELL "$OUTPUT" "$@"

