#!/usr/bin/env bash

set -euo pipefail

XSHELL="$1"; shift
INPUT="$1"; shift
OUTPUT=".x.$INPUT"

lenker "$INPUT" "$OUTPUT" | (grep -v "Wrote: $OUTPUT" || :)

$XSHELL "$OUTPUT" "$@"
RES=$?

rm "$OUTPUT"

exit $RES

